### ISSUE TITLE
Value should be newtype over `UInt 256` instead of BigNumber

### ISSUE THREAD

**Issue by safareli** [f-o-a-m/purescript-web3#113]

**Comment by blinky3713** [comment]
i'm actually going to go ahead and say "no" on on this one, for similar reasons that we had disagreements with the other hs-web3 maintainers. If you do this then for example you will make the `Transaction` type depend on the Solidity modules, which is just an inversion of dependencies.

 If you want the conversion from BigNumber to Value to fail because of a size or positivity issue, that's still worth talking about. You could also provide an iso somewhere, perhaps in the UInt module.
