### ISSUE TITLE
Build is broken after updating clickbait's geth

### ISSUE THREAD

**Issue by blinky3713** [f-o-a-m/purescript-web3#149]
According to @iostat the build is broken without dependency changes because of the geth upgrade implicit in the `foamspace/cliquebait:latest` docker image. 

I'm unsure what the real solution is. I mean to fix the build we just need to point to an older docker image in travis, but to fix the actual problem do we need to change something in chanterelle?

**Comment by kejace** [comment]
Fixed in #150

**Comment by iostat** [comment]
It's hard to tell what's going on in purescript-web3-tests -- but it seems like we're getting a revert (and it's hard to tell in which of the three `assertWeb3`s it's happening in). The change in the `cliquebait:latest` image likely triggered this -- since there's a newer version of geth/newer EVM/newer hardforks/EIPs, etc.

My hunches are that it's either
a) solc is too old somewhere transitively in the dependencies (and it's hard to tell where it's even coming from, it's not in package.json)
b) there was some kind of change in the EVM and purescript-web3's (haven't kept up with EIPs too much)
c) both?

Locking down the version to 1.9.12 seems like it's kind of a cop-out -- it's basically saying "yes, we work ethereum nodes, except like, the latest ones that mainnet uses now".
In fact, if anything 1.9.14 should be the one that breaks, as it has more EIPs implemented...

**Comment by iostat** [comment]
Closing in favor of #151. Latest geth is actually 1.10 series -- I can build up some cliquebait images for that
