### ISSUE TITLE
explore websocket support

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/purescript-web3#91]

**Comment by blinky3713** [comment]
Here is the api documentation https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB

This may necessitate a split on the Api module, between HTTP and WS apis

We probably want to abstract away the WS using coroutines producers or [aff-couroutines](https://github.com/purescript-contrib/purescript-aff-coroutines)  producer

**Comment by srghma** [comment]
or using https://github.com/purescript-halogen/purescript-halogen-subscriptions

which is copy of https://github.com/paf31/purescript-event

**Comment by srghma** [comment]
or maybe to remove conduit-transducers and implement 

1. https://hackage.haskell.org/package/machines
2. https://github.com/acowley/concurrent-machines/

https://www.youtube.com/watch?v=sEfn_x245mE (this video tells that machines are better than coroutines / iteratee haskell lib / trampoline based , the composition problem is solved INSIDE of lib)

My document with notes - https://docs.google.com/document/d/10Nge8-u6tOVBXSnmiED9fninrOOIP5C7mPhg6DEvAX0/edit?usp=sharing

--------

Actually the BEST way would be to use `/graphql` provided by geth

this way we would kill two rabbits at once:
- support batch requests
- support websockets (listening instead of polling)

but not all methods are implemented there (e.g. `eth_getXXX` methods)
AND most importantly it doesnt have support for subscriptions yet
https://github.com/ethereum/go-ethereum/issues/24518

![2022-03-09-12am-14-57-screenshot](https://user-images.githubusercontent.com/7573215/157334938-b43725d1-6e20-4c72-9e2b-f04c97a35dbe.png)
